# Generated by Django 5.1.4 on 2025-01-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='platillos',
            field=models.ManyToManyField(related_name='ingredientes', to='menu.platillo'),
        ),
    ]
